//Devices
export const LOAD_DEVICES_SUCCESS = "LOAD_DEVICES_SUCCESS"
export const BEGIN_LOAD_DEVICES = "BEGIN_LOAD_DEVICES"
export const END_LOAD_DEVICES = "END_LOAD_DEVICES"
export const SAVE_DEVICE_SUCCESS = "SAVE_DEVICE_SUCCESS"

//Other
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const END_AJAX_CALL = 'END_AJAX_CALL';
