//Devices All
export const LOAD_DEVICES_SUCCESS = "LOAD_DEVICES_SUCCESS"
export const BEGIN_LOAD_DEVICES = "BEGIN_LOAD_DEVICES"
export const END_LOAD_DEVICES = "END_LOAD_DEVICES"
//Devices One
export const LOAD_DEVICE_SUCCESS = "LOAD_DEVICE_SUCCESS"
export const BEGIN_LOAD_DEVICE = "BEGIN_LOAD_DEVICE"
export const END_LOAD_DEVICE = "END_LOAD_DEVICE"
export const SAVE_DEVICE_SUCCESS = "SAVE_DEVICE_SUCCESS"
export const RELOAD_DEVICE_DATATYPE_SUCCESS = "RELOAD_DEVICE_DATATYPE_SUCCESS"
//Device register New
export const BEGIN_REGISTER_IOT_DEVICE = "BEGIN_REGISTER_IOT_DEVICE"
export const REGISTER_IOT_DEVICE_SUCCESS = "REGISTER_IOT_DEVICE_SUCCESS"
export const END_REGISTER_IOT_DEVICE = "END_REGISTER_IOT_DEVICE"

//Commands
export const BEGIN_LOAD_DEVICE_COMMANDS = "BEGIN_LOAD_DEVICE_COMMANDS"
export const END_LOAD_DEVICE_COMMANDS = "END_LOAD_DEVICE_COMMANDS"
export const LOAD_DEVICE_COMMANDS_SUCCESS = "LOAD_DEVICE_COMMANDS_SUCCESS"
export const ACTIVATE_DEVICE_COMMAND_SUCCESS = "ACTIVATE_DEVICE_COMMAND_SUCCESS"
export const DEACTIVATE_DEVICE_COMMAND_SUCCESS = "DEACTIVATE_DEVICE_COMMAND_SUCCESS"
export const UPDATE_LOCATION_COMMAND_SUCCESS = "UPDATE_LOCATION_COMMAND_SUCCESS"
export const CHANGE_INTERVAL_COMMAND_SUCCESS = "CHANGE_INTERVAL_COMMAND_SUCCESS"

//DeviceData
export const BEGIN_LOAD_DEVICE_DATA = "BEGIN_LOAD_DEVICE_DATA"
export const END_LOAD_DEVICE_DATA = "END_LOAD_DEVICE_DATA"
export const LOAD_DEVICE_DATA_SUCCESS = "LOAD_DEVICE_DATA_SUCCESS"

//TTN existing ttm info on IOT device
export const BEGIN_SAVE_EXISTING_TTN_DEVICE = "BEGIN_SAVE_EXISTING_TTN_DEVICE"
export const END_SAVE_EXISTING_TTN_DEVICE = "END_SAVE_EXISTING_TTN_DEVICE"
export const SAVE_EXISTING_TTN_DEVICE_SUCCESS = "SAVE_EXISTING_TTN_DEVICE_SUCCESS"
//TTN new
export const BEGIN_REGISTER_NEW_TTN_DEVICE = "BEGIN_REGISTER_NEW_TTN_DEVICE"
export const END_REGISTER_NEW_TTN_DEVICE = "END_REGISTER_NEW_TTN_DEVICE"
export const REGISTER_NEW_TTN_DEVICE_SUCCESS = "REGISTER_NEW_TTN_DEVICE_SUCCESS"
//TTN delete ttn info on IOT device
export const BEGIN_DELETE_TTN_DEVICE_INFO = "BEGIN_DELETE_TTN_DEVICE_INFO"
export const END_DELETE_TTN_DEVICE_INFO = "END_DELETE_TTN_DEVICE_INFO"
export const DELETE_TTN_DEVICE_INFO_SUCCESS = "DELETE_TTN_DEVICE_INFO_SUCCESS"
//TTN extended Info
export const BEGIN_LOAD_EXTENDED_TTN_INFO = "BEGIN_LOAD_EXTENDED_TTN_INFO"
export const END_LOAD_EXTENDED_TTN_INFO = "END_LOAD_EXTENDED_TTN_INFO"
export const LOAD_EXTENDED_TTN_INFO_SUCCESS = "LOAD_EXTENDED_TTN_INFO_SUCCESS"
//TTN app Info
export const BEGIN_LOAD_TTN_APPLICATION_INFO = "BEGIN_LOAD_TTN_APPLICATION_INFO"
export const END_LOAD_TTN_APPLICATION_INFO = "END_LOAD_TTN_APPLICATION_INFO"
export const LOAD_TTN_APPLICATION_INFO_SUCCESS = "LOAD_TTN_APPLICATION_INFO_SUCCESS"
//TTN load devices
export const BEGIN_LOAD_TTN_DEVICES= "BEGIN_LOAD_TTN_DEVICES"
export const END_LOAD_TTN_DEVICES = "END_LOAD_TTN_DEVICES"
export const LOAD_TTN_DEVICES_SUCCESS = "LOAD_TTN_DEVICES_SUCCESS"
//TTN delete
export const BEGIN_DELETE_TTN_DEVICE= "BEGIN_DELETE_TTN_DEVICE"
export const END_DELETE_TTN_DEVICE = "END_DELETE_TTN_DEVICE"
export const DELETE_TTN_DEVICE_SUCCESS = "DELETE_TTN_DEVICE_SUCCESS"



//Other
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
